### ISSUE TITLE
current game info wss events

### ISSUE THREAD

**Issue by uptotec** [techchrism/valorant-api-docs#31]
I'm traying to find a local wss current game events like kda for local player, current game phase and when the local player dies. I was able to get the current game score from the "OnJsonApiEvent_chat_v4_presences" but nothing about what happened in the round.
I found the data I want on OverWolf [here](https://overwolf.github.io/api/games/events/valorant) So, I know they exist but, I'm unable to find them.
I would appreciate the help.

**Comment by techchrism** [comment]
Unfortunately, as far as I'm aware, Overwolf is reading values directly from game memory. It's not recommended you try this yourself because it could have bad interactions with Vanguard.

You can either use Overwolf (gross, I know) or make a high-effort workaround using screen-grabbing functionality and trying to parse kills from the agent icons or something like that.
