### ISSUE TITLE
CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by GamingInfinite** [techchrism/valorant-api-docs#55]
I dont know what this error means, I looked into it and it said that its related to ssl certificates, but outside of playing around with smaller apis, I don't know how to fix this.  I'm gonna keep tinkering with it just to see if i can find a way around this but I'd appreciate any help

**Comment by techchrism** [comment]
Is this for a local endpoint?

If so, all of those responses are self-signed. You can ignore errors related to self-signed certs (depends on your request library).

I'll leave this issue open because I thought I noted that local endpoint responses are self-signed but from a quick glance, this doesn't seem to be in the docs.

**Comment by GamingInfinite** [comment]
It is for a local endpoint (mostly because it seems simpler).  I'm using a fetch request in a (browser-like) environment and I've poked around for a bit but haven't found anything on how to disable it through that.

**Comment by techchrism** [comment]
In a browser, it will be immensely inconvenient or impossible. You'd have to explicitly allow the self-signed certificate, but even then, the local api does not have CORS headers.

**Comment by GamingInfinite** [comment]
ok...  if i decide to pursue this project further, it does have a rust backend, its just really frustrating and convoluted to use, but I should be able to make the api calls properly through that, as I have found a rust package that allows disregarding tsl errors.  closing issue
