### ISSUE TITLE
Enable GitHub Pages

### ISSUE THREAD

**Issue by NyCodeGHG** [techchrism/valorant-api-docs#7]
hi, i think it would be nice to be able to read the documentation in the browser without all the github ui. [GitHub Pages](https://pages.github.com) would be great for this because they can render markdown straight to html without any further configuration. You would just have to enable it in your repo settings.

GitHub Pages Configuration:
![Screenshot_20220123-030750](https://user-images.githubusercontent.com/37078297/150661869-b2916f03-158e-4849-a6be-c6e944521aaa.png)

It would look like [this](https://nycodeghg.github.io/valorant-api-docs). I would love it if you could enable that.

**Comment by techchrism** [comment]
Enabled 👍
I was planning in the future to create a fancier website or something but this'll work for now. Not letting perfect be the enemy of good and all that.
I'll have to add request categories in the base readme but for now they can be accessed directly by url.
Linking to specific requests also doesn't work optimally since it links to the markdown version.

**Comment by NyCodeGHG** [comment]
thank you :)
